$a = 103

all:
	mkdir ../modules/${a}
	mv * ../modules/${a}
	mkdir pack
	mkdir subpack
	cp Bp.java pack/App.java
m:
	mkdir ../modules/${a}
	mv pack ../modules/${a}
	mkdir pack
	cp Bp.java pack/App.java
